import { createApp } from "vue";
import App from "./app.vue";
import "../lib/styles/button.css";
import "../lib/styles/avatar.css";
import "../lib/styles/col.css";
import "../lib/styles/row.css";
import "../lib/styles/header.css";
import "../lib/styles/footer.css";
import "../lib/styles/container.css";
import "../lib/styles/main.css";
import "../lib/styles/aside.css";
import "../lib/styles/carousel.css";
import "../lib/styles/carousel-item.css";
import "../lib/styles/icon.css";
import "../lib/styles/switch.css";
const app = createApp(App);
app.mount("#app");
